package com.easyparking.dao;

import java.util.List;

import com.easyparking.entity.CarInfo;
import com.easyparking.util.EasyParkingException;


 
/**
 * DAO interface for table: CarInfo.
 * @author autogenerated
 */
public class CarInfoDao extends GenericDao< Integer,CarInfo> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// constructor only
	
	public CarInfo findByUserId(Integer userId) throws EasyParkingException{
		List<CarInfo> list = findByNamedQuery("CarInfo.findByUserId", "userId", userId);
		if(list.size() > 0){
			return list.get(0);
		}
		return null;
	}
	
	
}

