package com.easyparking.dao;

import com.easyparking.entity.CarParkingMapping;

 
/**
 * DAO interface for table: CarParkingMapping.
 * @author autogenerated
 */
public class CarParkingMappingDao extends GenericDao<Integer,CarParkingMapping>  {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// constructor only
}

