package com.easyparking.dao;

import java.util.List;

import org.springframework.transaction.annotation.Transactional;

import com.easyparking.entity.ParkingLot;
import com.easyparking.entity.User;
import com.easyparking.util.EasyParkingException;

 
/**
 * DAO interface for table: ParkingLot.
 * @author autogenerated
 */
public class ParkingLotDao extends GenericDao<Integer,ParkingLot>  {
	// constructor only
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public List<ParkingLot> findByOwnerId(Integer ownerId) throws EasyParkingException{
		List<ParkingLot> parkingList = findByNamedQuery("ParkingLot.findByOwnerId", "ownerId", ownerId);
		if(parkingList != null){
			return parkingList;
		}
		return null;
	}
	
}

