package com.easyparking.dao;

import com.easyparking.entity.Parker;

/**
 * DAO interface for table: Parker.
 * @author autogenerated
 */
public class ParkerDao extends GenericDao<Integer,Parker>  {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// constructor only
}

