package com.easyparking.dao;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;

import com.easyparking.entity.User;
import com.easyparking.util.EasyParkingException;

 
/**
 * DAO interface for table: User.
 * @author autogenerated
 */
public class UserDao extends GenericDao<Integer,User>  {

	@Autowired
	private UserDao userDao;
	
	public User findByUserId(Integer userId) throws EasyParkingException{
		List<User> list = findByNamedQuery("User.findByUserId", "userId", userId);
		if(list.size() > 0){
			return list.get(0);
		}
		return null;
	}
	
	public User findByEmailId(String email) throws EasyParkingException{
		List<User> list = findByNamedQuery("User.findByEmail", "email", email);
		if(list.size() > 0){
			return list.get(0);
		}
		return null;
	}
	
	@Transactional
	public boolean saveAndUpdateUser(User user){
		try{
			if(user.getId() ==null || user.getId() == 0){
				userDao.persist(user);
				return true;
			}else{
				userDao.merge(user);
				return true;
			}
		}catch(Exception ex){
			ex.printStackTrace();
		}
		return false;
	}
	 
}

