package com.easyparking.dao;

import com.easyparking.entity.UserCarMapping;

 
/**
 * DAO interface for table: UserCarMapping.
 * @author autogenerated
 */
public class UserCarMappingDao extends GenericDao<Integer,UserCarMapping>  {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// constructor only
}

