package com.easyparking.entity;

import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.Map;
import java.util.WeakHashMap;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.proxy.HibernateProxy;


/** 
 * Object mapping for hibernate-handled table: parker.
 * @author autogenerated
 */

@Entity
@Table(name = "parker")
public class Parker extends BaseEntity<Integer>implements  Serializable {

	/** Serial Version UID. */
	private static final long serialVersionUID = -558968828L;

	

	/** Field mapping. */
	private String address;
	/** Field mapping. */
	private String altitude;
	/** Field mapping. */
	private String city;
	/** Field mapping. */
	private Date createdAt;
	/** Field mapping. */
	private String createdBy;
	/** Field mapping. */
	private String emailId;
	/** Field mapping. */
	private Integer id = 0; // init for hibernate bug workaround
	/** Field mapping. */
	private String longitude;
	/** Field mapping. */
	private String mobileNo;
	/** Field mapping. */
	private String name;
	/** Field mapping. */
	private String pin;
	/** Field mapping. */
	private String state;
	/** Field mapping. */
	private Date updatedAt;
	/** Field mapping. */
	private String updatedBy;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Parker() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Parker(Integer id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param address String object;
	 * @param city String object;
	 * @param emailId String object;
	 * @param id Long object;
	 * @param mobileNo String object;
	 * @param name String object;
	 */
	public Parker(String address, String city, String emailId, 					
			Integer id, String mobileNo, String name) {

		this.address = address;
		this.city = city;
		this.emailId = emailId;
		this.id = id;
		this.mobileNo = mobileNo;
		this.name = name;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Parker.class;
	}
 

    /**
     * Return the value associated with the column: address.
	 * @return A String object (this.address)
	 */
	@Basic( optional = false )
	@Column( nullable = false, length = 250  )
	public String getAddress() {
		return this.address;
		
	}
	

  
    /**  
     * Set the value related to the column: address.
	 * @param address the address value you wish to set
	 */
	public void setAddress(final String address) {
		this.address = address;
	}

    /**
     * Return the value associated with the column: altitude.
	 * @return A String object (this.altitude)
	 */
	@Basic( optional = true )
	@Column( length = 250  )
	public String getAltitude() {
		return this.altitude;
		
	}
	

  
    /**  
     * Set the value related to the column: altitude.
	 * @param altitude the altitude value you wish to set
	 */
	public void setAltitude(final String altitude) {
		this.altitude = altitude;
	}

    /**
     * Return the value associated with the column: city.
	 * @return A String object (this.city)
	 */
	@Basic( optional = false )
	@Column( nullable = false, length = 20  )
	public String getCity() {
		return this.city;
		
	}
	

  
    /**  
     * Set the value related to the column: city.
	 * @param city the city value you wish to set
	 */
	public void setCity(final String city) {
		this.city = city;
	}

    /**
     * Return the value associated with the column: createdAt.
	 * @return A Date object (this.createdAt)
	 */
	@Basic( optional = true )
	@Column( name = "created_at"  )
	public Date getCreatedAt() {
		return this.createdAt;
		
	}
	

  
    /**  
     * Set the value related to the column: createdAt.
	 * @param createdAt the createdAt value you wish to set
	 */
	public void setCreatedAt(final Date createdAt) {
		this.createdAt = createdAt;
	}

    /**
     * Return the value associated with the column: createdBy.
	 * @return A String object (this.createdBy)
	 */
	@Basic( optional = true )
	@Column( name = "created_by", length = 250  )
	public String getCreatedBy() {
		return this.createdBy;
		
	}
	

  
    /**  
     * Set the value related to the column: createdBy.
	 * @param createdBy the createdBy value you wish to set
	 */
	public void setCreatedBy(final String createdBy) {
		this.createdBy = createdBy;
	}

    /**
     * Return the value associated with the column: emailId.
	 * @return A String object (this.emailId)
	 */
	@Basic( optional = false )
	@Column( name = "email_id", nullable = false, length = 250  )
	public String getEmailId() {
		return this.emailId;
		
	}
	

  
    /**  
     * Set the value related to the column: emailId.
	 * @param emailId the emailId value you wish to set
	 */
	public void setEmailId(final String emailId) {
		this.emailId = emailId;
	}

    /**
     * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
    @Id 
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Basic( optional = false )
	@Column( name = "id", nullable = false  )
	public Integer getId() {
		return this.id;
		
	}
	

  

    /**
     * Return the value associated with the column: longitude.
	 * @return A String object (this.longitude)
	 */
	@Basic( optional = true )
	@Column( length = 250  )
	public String getLongitude() {
		return this.longitude;
		
	}
	

  
    /**  
     * Set the value related to the column: longitude.
	 * @param longitude the longitude value you wish to set
	 */
	public void setLongitude(final String longitude) {
		this.longitude = longitude;
	}

    /**
     * Return the value associated with the column: mobileNo.
	 * @return A String object (this.mobileNo)
	 */
	@Basic( optional = false )
	@Column( name = "mobile_no", nullable = false, length = 15  )
	public String getMobileNo() {
		return this.mobileNo;
		
	}
	

  
    /**  
     * Set the value related to the column: mobileNo.
	 * @param mobileNo the mobileNo value you wish to set
	 */
	public void setMobileNo(final String mobileNo) {
		this.mobileNo = mobileNo;
	}

    /**
     * Return the value associated with the column: name.
	 * @return A String object (this.name)
	 */
	@Basic( optional = false )
	@Column( nullable = false, length = 250  )
	public String getName() {
		return this.name;
		
	}
	

  
    /**  
     * Set the value related to the column: name.
	 * @param name the name value you wish to set
	 */
	public void setName(final String name) {
		this.name = name;
	}

    /**
     * Return the value associated with the column: pin.
	 * @return A String object (this.pin)
	 */
	@Basic( optional = true )
	@Column( length = 11  )
	public String getPin() {
		return this.pin;
		
	}
	

  
    /**  
     * Set the value related to the column: pin.
	 * @param pin the pin value you wish to set
	 */
	public void setPin(final String pin) {
		this.pin = pin;
	}

    /**
     * Return the value associated with the column: state.
	 * @return A String object (this.state)
	 */
	@Basic( optional = true )
	@Column( length = 20  )
	public String getState() {
		return this.state;
		
	}
	

  
    /**  
     * Set the value related to the column: state.
	 * @param state the state value you wish to set
	 */
	public void setState(final String state) {
		this.state = state;
	}

    /**
     * Return the value associated with the column: updatedAt.
	 * @return A Date object (this.updatedAt)
	 */
	@Basic( optional = true )
	@Column( name = "updated_at"  )
	public Date getUpdatedAt() {
		return this.updatedAt;
		
	}
	

  
    /**  
     * Set the value related to the column: updatedAt.
	 * @param updatedAt the updatedAt value you wish to set
	 */
	public void setUpdatedAt(final Date updatedAt) {
		this.updatedAt = updatedAt;
	}

    /**
     * Return the value associated with the column: updatedBy.
	 * @return A String object (this.updatedBy)
	 */
	@Basic( optional = true )
	@Column( name = "updated_by", length = 250  )
	public String getUpdatedBy() {
		return this.updatedBy;
		
	}
	

  
    /**  
     * Set the value related to the column: updatedBy.
	 * @param updatedBy the updatedBy value you wish to set
	 */
	public void setUpdatedBy(final String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Override
	public void setId(Integer id) {
		this.id=id;
	}


  
	



	
}
