package com.easyparking.entity;

import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.Map;
import java.util.WeakHashMap;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.proxy.HibernateProxy;


/** 
 * Object mapping for hibernate-handled table: user_car_mapping.
 * @author autogenerated
 */

@Entity
@Table(name = "user_car_mapping")
public class UserCarMapping extends BaseEntity<Integer> implements Cloneable, Serializable {

	/** Serial Version UID. */
	private static final long serialVersionUID = -558968825L;

	/** Field mapping. */
	private Integer carId;
	/** Field mapping. */
	private Date createdAt;
	/** Field mapping. */
	private String createdBy;
	/** Field mapping. */
	private Integer id = 0; // init for hibernate bug workaround
	/** Field mapping. */
	private Date updatedAt;
	/** Field mapping. */
	private String updatedBy;
	/** Field mapping. */
	private Integer userId;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public UserCarMapping() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public UserCarMapping(Integer id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param carId Integer object;
	 * @param id Long object;
	 * @param userId Integer object;
	 */
	public UserCarMapping(Integer carId, Integer id, Integer userId) {

		this.carId = carId;
		this.id = id;
		this.userId = userId;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return UserCarMapping.class;
	}
 

    /**
     * Return the value associated with the column: carId.
	 * @return A Integer object (this.carId)
	 */
	@Basic( optional = false )
	@Column( name = "car_id", nullable = false  )
	public Integer getCarId() {
		return this.carId;
		
	}
	

  
    /**  
     * Set the value related to the column: carId.
	 * @param carId the carId value you wish to set
	 */
	public void setCarId(final Integer carId) {
		this.carId = carId;
	}

    /**
     * Return the value associated with the column: createdAt.
	 * @return A Date object (this.createdAt)
	 */
	@Basic( optional = true )
	@Column( name = "created_at"  )
	public Date getCreatedAt() {
		return this.createdAt;
		
	}
	

  
    /**  
     * Set the value related to the column: createdAt.
	 * @param createdAt the createdAt value you wish to set
	 */
	public void setCreatedAt(final Date createdAt) {
		this.createdAt = createdAt;
	}

    /**
     * Return the value associated with the column: createdBy.
	 * @return A String object (this.createdBy)
	 */
	@Basic( optional = true )
	@Column( name = "created_by", length = 250  )
	public String getCreatedBy() {
		return this.createdBy;
		
	}
	

  
    /**  
     * Set the value related to the column: createdBy.
	 * @param createdBy the createdBy value you wish to set
	 */
	public void setCreatedBy(final String createdBy) {
		this.createdBy = createdBy;
	}

    /**
     * Return the value associated with the column: id.
	 * @return A Long object (this.id)
	 */
    @Id 
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Basic( optional = false )
	@Column( name = "id", nullable = false  )
	public Integer getId() {
		return this.id;
		
	}
	

  

    /**
     * Return the value associated with the column: updatedAt.
	 * @return A Date object (this.updatedAt)
	 */
	@Basic( optional = true )
	@Column( name = "updated_at"  )
	public Date getUpdatedAt() {
		return this.updatedAt;
		
	}
	

  
    /**  
     * Set the value related to the column: updatedAt.
	 * @param updatedAt the updatedAt value you wish to set
	 */
	public void setUpdatedAt(final Date updatedAt) {
		this.updatedAt = updatedAt;
	}

    /**
     * Return the value associated with the column: updatedBy.
	 * @return A String object (this.updatedBy)
	 */
	@Basic( optional = true )
	@Column( name = "updated_by", length = 250  )
	public String getUpdatedBy() {
		return this.updatedBy;
		
	}
	

  
    /**  
     * Set the value related to the column: updatedBy.
	 * @param updatedBy the updatedBy value you wish to set
	 */
	public void setUpdatedBy(final String updatedBy) {
		this.updatedBy = updatedBy;
	}

    /**
     * Return the value associated with the column: userId.
	 * @return A Integer object (this.userId)
	 */
	@Basic( optional = false )
	@Column( name = "user_id", nullable = false  )
	public Integer getUserId() {
		return this.userId;
		
	}
	

  
    /**  
     * Set the value related to the column: userId.
	 * @param userId the userId value you wish to set
	 */
	public void setUserId(final Integer userId) {
		this.userId = userId;
	}

	@Override
	public void setId(Integer id) {
		// TODO Auto-generated method stub
		
	}


	

	
}
